version: '3'

services:
  payment-verification-system-frontend:
    build:
      context: /home/collins/Desktop/payment-verification-system-frontend/payment-verification-system-frontend
    ports:
      - "5173:80"

  mongodb:
    image: mongo:latest
    container_name: mongodatabase
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


  payment-verification-system:
    build:
      context: /home/collins/Desktop/payment-verification-system
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
     MONGO_DB_URI: mongodb://localhost:27017/pvs

  payment-verification-system-websocket:
    build:
      context: /home/collins/Desktop/payment-verification-system-websocket
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
volumes:
    mongodb_data:

